import type { Instrument } from './types';

export const INSTRUMENTS: Instrument[] = [
  {
    id: 'tts',
    name: 'Text-to-speech',
    category: 'digital-prosthetic',
    description: 'Have written text read aloud.',
    lifts: { reading: 30, words: 10, holding: 5 },
    toolLine: 'contested',
    externalLink: 'https://neurodiversity.tools',
  },
  {
    id: 'stt',
    name: 'Speech-to-text',
    category: 'digital-prosthetic',
    description: 'Speak your thoughts and let the machine write.',
    lifts: { writing: 30, words: 10 },
    toolLine: 'contested',
    externalLink: 'https://neurodiversity.tools',
  },
  {
    id: 'mindmap',
    name: 'Mind-mapping',
    category: 'digital-prosthetic',
    description: 'Externalise structure spatially before sequencing words.',
    lifts: { planning: 20, space: 10, writing: 10, puzzles: 5 },
    toolLine: 'accepted',
  },
  {
    id: 'taskmgr',
    name: 'Task manager',
    category: 'digital-prosthetic',
    description: 'Offload holding and sequencing to a trusted outside surface.',
    lifts: { planning: 25, holding: 20, focus: 10 },
    toolLine: 'accepted',
  },
  {
    id: 'calc',
    name: 'Calculator & maths aids',
    category: 'digital-prosthetic',
    description: 'Route around arithmetic so reasoning can run.',
    lifts: { numbers: 25, puzzles: 5, quick: 10 },
    toolLine: 'accepted',
  },
  {
    id: 'breath',
    name: 'Breathwork',
    category: 'mind-body',
    description: 'Steady the body so cognition has somewhere to land.',
    lifts: { focus: 15, planning: 5 },
    toolLine: 'accepted',
  },
  {
    id: 'movement',
    name: 'Movement & fidget',
    category: 'mind-body',
    description: 'Bodies that can move think differently.',
    lifts: { focus: 20, quick: 5 },
    toolLine: 'contested',
  },
  {
    id: 'metacog',
    name: 'Notice & name',
    category: 'mind-body',
    description: 'Catch the pattern and choose again.',
    lifts: { planning: 15, focus: 10 },
    toolLine: 'accepted',
  },
  {
    id: 'peers',
    name: 'Neurodivergent peers',
    category: 'relational',
    description: 'Find yourself surprised and delighted by different minds.',
    lifts: { planning: 10, words: 10, focus: 5 },
    toolLine: 'accepted',
  },
  {
    id: 'collective-reflection',
    name: 'Collective reflection',
    category: 'relational',
    description: 'Sense-making together — "Have you tried…".',
    lifts: { planning: 10, words: 5, writing: 5 },
    toolLine: 'accepted',
  },
  {
    id: 'quiet',
    name: 'Noise-calmed space',
    category: 'space-making',
    description: 'Less sensory noise, more attention to keep.',
    lifts: { focus: 25, holding: 10, reading: 10 },
    toolLine: 'contested',
  },
  {
    id: 'rhizomatic',
    name: 'Rhizomatic pedagogy',
    category: 'space-making',
    description: 'Learning that meanders rather than marches.',
    lifts: { puzzles: 15, words: 10, space: 10 },
    toolLine: 'contested',
  },
];
